var { Schema , model } = require('mongoose');

var studentSchema = new Schema({
    surname:{
        type:String
    },
    studentname:{
        type:String
    },
    fathername:{
        type:String
    },
    studentMobile:{
        type:String
    },
    studentWhatsapp:{
        type:String
    },
    parentMobile:{
        type:String
    },
    parentWhatsapp:{
        type:String
    },
    address:{
        type:String
    },
    date:{
        type:String
    },
    image:{
        type:String
    },
    qualification:{
        type:String
    },
    references:{
        type:String
    },
    referencesName:{
        type:String
    },
    course:{
        type:String
    },
    courseDuration:{
        type:String
    },
    dailyTime:{
        type:String
    },
    courseContent:{
        type:String
    },
    totalFees:{
        type:String
    },
    joiningDate:{
        type:String
    },
    endingDate:{
        type:String
    },
    jobResponse:{
        type:String
    },
    installmentDetails:{
        type:String
    },
    installmentDetails1:{
        type:String
    },
    installmentDetails2:{
        type:String
    },
    installmentDetails3:{
        type:String
    },
    feculty:{
        type:String
    },
    batch:{
        type:String
    },
    runningTopic:{
        type:String
    },
    pc_laptop:{
        type:String
    },
    pcNo:{
        type:String
    },
    laptopCompulsory:{
        type:String
    },
    extraNote:{
        type:String
    },
    receptionNote:{
        type:String
    },
});

var Student = new model("Student",studentSchema);

module.exports = Student